# Header
nav:
  Posts: /archives
  # Categories: /category
  # Tags: /tag

# favicon
favicon: /images/favicon.jpg

# logo
logo: /images/logo.svg

# links
links:
  Github: https://github.com/oxmyxo
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: false

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: true
  repo: Oxmyxo/blog
  repo_id: R_kgDOSfvY4Q
  category: General
  category_id: DIC_kwDOSfvY4c4C9Oix
  mapping: pathname

# maple
maple:
  enable: true
  # fall leaf count
  count: 5
  # 0-1
  speed: 0.3

